### ISSUE TITLE
Feature Request: Add support for internal app sharing

### ISSUE THREAD

**Issue by jd-lacey** [r0adkll/upload-google-play#10]
Google Play console allows apps to be uploaded for "Internal App Sharing". Not sure whether this is considered a "track" but I didn't see it mentioned in the list of values for `track`.

**Comment by palvarez89** [comment]
On the readme it says:

> ### `track`
>
> **Required:** The track in which you want to assign the uploaded app.  
> **Default:** `production`  
> _Values:_ `alpha`, `beta`, `internal`, `production`

I assume `track: internal` is what you want.

**Comment by r0adkll** [comment]
@palvarez89 That is just for the "Internal" track in the release management console. What @jd-lacey is referring to is a different release mechanism entirely in the console. I believe this is the documentation in the API for that method (https://developers.google.com/android-publisher/api-ref/internalappsharingartifacts) which will require a modified implementation from how this action publishes to alpha, beta, production, etc. 

I'm going to start working on this as soon as I can.

**Comment by vitusortner** [comment]
Did you get to look into it already? If not, I'd gladly take over that task.

**Comment by r0adkll** [comment]
@vitusortner I just resolved the issue now. It should be available in a moment on the tag `v1`. You can now set the track to `internalsharing` and it will attempt to upload the apk/bundle to internal app sharing. If successful it will set the output `internalSharingDownloadUrl` and the following environment variable: `INTERNAL_SHARING_DOWNLOAD_URL`

**Comment by juanma-lora-pepephone** [comment]
I don't see the url in ${{ steps.<step_id>.outputs.internalSharingDownloadUrl }} neither in ${{ env.INTERNAL_SHARING_DOWNLOAD_URL}} and the upload is successful. Has anyone the same problem?

**Comment by forntoh** [comment]
> I don't see the url in ${{ steps.<step_id>.outputs.internalSharingDownloadUrl }} neither in ${{ env.INTERNAL_SHARING_DOWNLOAD_URL}} and the upload is successful. Has anyone the same problem?

I have the same problem, the env var doesn't exist

**Comment by juanma-lora-pepephone** [comment]
I opened an issue: https://github.com/r0adkll/upload-google-play/issues/26
