### ISSUE TITLE
Extract packageName from apk/aab

### ISSUE THREAD

**Issue by jopmiddelkamp** [r0adkll/upload-google-play#103]
Why is the `packageName` required? This should be extracted from the apk/aab file.

**Comment by boswelja** [comment]
I like it! Have you got any sources for reading the package name of APK/AABs?

**Comment by FunkyMuse** [comment]
> I like it! Have you got any sources for reading the package name of APK/AABs?

[APK ](https://stackoverflow.com/a/37324607) 

[AAB](https://stackoverflow.com/a/60158478)

**Comment by boswelja** [comment]
> > I like it! Have you got any sources for reading the package name of APK/AABs?
> 
> [APK ](https://stackoverflow.com/a/37324607)
> 
> [AAB](https://stackoverflow.com/a/60158478)

I'd like to avoid bundling extra binaries ourselves if possible. Do you have any solutions that can be deployed via npm packages (or better yet, no extra dependencies)?

**Comment by boswelja** [comment]
I am closing this, since I can't seem to find any solutions that won't significantly increase the size of the bundled action. If you find anything, please create a new issue
