### ISSUE TITLE
##[error]The caller does not have permission

### ISSUE THREAD

**Issue by josealfonsomora** [r0adkll/upload-google-play#11]
Getting this error before upload the bundle or apk

https://github.com/josealfonsomora/Three-Balance-Check/runs/726757957?check_suite_focus=true

There has to be something that I'm doing wrong but the lack of logs at this part does not help

Do you know what can happen? 
Can we add more logs?

**Comment by josealfonsomora** [comment]
I had wrong permissions at google play console. Closing the issue

**Comment by DPigeon** [comment]
> I had wrong permissions at google play console. Closing the issue

What permissions did you set exactly? I set all the correct permissions such as owner with the proper RELEASE MANAGEMENT permissions but I still get the `##[error]The caller does not have permission` error.

**Comment by josealfonsomora** [comment]
At google play console I didn't add this permission

![Google Play](https://miro.medium.com/max/700/1*JXKEAqbzf4-kLnz2gE2b-g.png)

I wrote a little guide because of the permission problems  [Medium post](https://medium.com/@josealfonsomora/publishing-android-apps-with-github-actions-3cb9a90396ca)

**Comment by DPigeon** [comment]
> At google play console I didn't add this permission
> 
> ![Google Play](https://camo.githubusercontent.com/4856102ceb1148ce374e747fe8f6a72a37862242/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f3730302f312a4a584b454171627a66342d6b4c6e7a32674532622d672e706e67)
> 
> I wrote a little guide because of the permission problems [Medium post](https://medium.com/@josealfonsomora/publishing-android-apps-with-github-actions-3cb9a90396ca)

Thanks !
However, I did mostly everything on this tutorial except for:
- Granting permission to gradlew at the beginning of the workflow
- Uploading a manual file app before

So do you think I need to do those 2 things before? Are they needed things?

**Comment by josealfonsomora** [comment]
> Uploading a manual file app before

That is important, but the error will be different (something like "the track does not exist)

Take a look to the app that you granted the permissions, maybe you have more than one permission at your Google Play Console and you are not granting permissions to the new app

Gradle permission should give you another error building the apk and I believe your error is uploading

I would recommend remove the service account that you have created and follow the steps from my guide, starting from the google play console

**Comment by DPigeon** [comment]
> > Uploading a manual file app before
> 
> That is important, but the error will be different (something like "the track does not exist)
> 
> Take a look to the app that you granted the permissions, maybe you have more than one permission at your Google Play Console and you are not granting permissions to the new app
> 
> Gradle permission should give you another error building the apk and I believe your error is uploading
> 
> I would recommend remove the service account that you have created and follow the steps from my guide, starting from the google play console

Yes for the gradlew permission I can build my apk and sign it without any errors so that is not a problem.

For the other step, you're right. I probably need to upload a manual file before so that it knows which app the account service is refering to if that makes sense? I see that this may be the step that I am missing.

**Comment by banool** [comment]
I'm having trouble with this too, it seems the UI for creating a service account has changed.

**Comment by 2manoj1** [comment]
facing same issue. made owner role also android management user. Provide admin grant access in play console and added app permission. Getting same issue.

**Comment by DPigeon** [comment]
I remember I had to upload a signed .apk or .aab file to my project app to make it work before being able to use this action.

**Comment by 2manoj1** [comment]
@DPigeon previous APK already in play console. Also uploaded manually. It's running in production.

**Comment by PhongPham0909** [comment]
I have the same issue with you. Can you tell me: how to grant permission to avoid that issue. Thanks

**Comment by bloodring** [comment]
I have the same issue as well! Have you guys already found a solution?

**Comment by nvacheishvili** [comment]
I also have this issue and what's up with this

**Comment by boswelja** [comment]
> I'm having trouble with this too, it seems the UI for creating a service account has changed.
> 
> **Update**: The solution was to make sure I gave my service account the proper permissions when making it at step 2. In this guide (https://developers.google.com/android/management/service-account), don't ignore the part about giving it the "Android Management API" role. The wizard says step 2 is optional, but for this purpose it is not. Then make sure to go to "API Access" here (https://play.google.com/apps/publish) and grant access to the role.

This is the solution. Any delays or further permission issues are on Google's side, but it's more than likely a misconfiguration on your end.

We are unable to "fix" this at the action level because there is nothing to fix.
