### ISSUE TITLE
Upload "Instant app only" to some track

### ISSUE THREAD

**Issue by miduch** [r0adkll/upload-google-play#124]
Is it possible to use this action to create a draft release + uplaod aab to Instant App only? 
When you have Instant app support enabled, using this action always creates a new draft/release for Standard release type only. 

Instant apps can be enabled from Advanced settings > Add release type > Google Play Instant

After doing that in Tracks popup appears where you can select Standard, Instant App only e.t.c. 

<img width="800" alt="Screenshot 2022-06-23 at 11 03 59" src="https://user-images.githubusercontent.com/22243296/175251044-cc707599-a9ce-44e6-821c-0c531a25d82e.png">

**Comment by boswelja** [comment]
We don't currently have support for Instant Apps. How different is the upload process? If it's reasonably similar we can add it as a feature to this action. If not, a separate action might be a better idea

**Comment by boswelja** [comment]
After checking out the Edits API, I am unable to find instant app information. This implies either there is no API, or the API does not exist as part of the Edits API. In either case, that means it's probably not a good idea to support it here unfortunately.

If anything changes, please reopen this or create a new issue

**Comment by miduch** [comment]
https://issuetracker.google.com/issues/256669316
