### ISSUE TITLE
Fails but no error is showed

### ISSUE THREAD

**Issue by Garyfimo** [r0adkll/upload-google-play#13]
Hey, I'm getting this fail, but it says much 
![image](https://user-images.githubusercontent.com/5316995/85924822-44db1f80-b85a-11ea-91a5-a42596b91b81.png)

This is my job :)

  uploadAPK:
    name: Upload APK to Google Play
    runs-on: ubuntu-latest
    needs: buildAPK
    steps:
      - uses: actions/checkout@v2
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
         name: app-release
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH }}
          packageName: com.garyfimo.unittestexample
          releaseFile: app-release
          track: production
          userFraction: 0.15
          whatsNewDirectory: whatsNew

**Comment by Garyfimo** [comment]
![image](https://user-images.githubusercontent.com/5316995/85924846-705e0a00-b85a-11ea-81cc-ca37e522be77.png)

**Comment by r0adkll** [comment]
Could you follow the steps here (https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging) and add the secret to your repository `ACTIONS_STEP_DEBUG` to `true` and then re-run your action and further post the output from your run?

**Comment by Garyfimo** [comment]
Hey, thanks for answering...
![image](https://user-images.githubusercontent.com/5316995/86028901-1bf09100-b9f8-11ea-8774-f4a1babcc5af.png)
![image](https://user-images.githubusercontent.com/5316995/86028923-24e16280-b9f8-11ea-8b30-f3815764ec1e.png)

I'm thinking  **serviceAccountJsonPlainText** has to be use, because I'm using **serviceAccountJson**

**Comment by r0adkll** [comment]
I don't think that's the problem as the code checks for either and would throw a well-defined error if it was.

What I think is happening is that the action depends on the extension on the release file `.apk` or `.aab` but it looks like you are downloading the artifact without one. Try updating your previous step to set the name to `app-release.apk` and updating the `releaseFile: app-release.apk` argument for this action.

**Comment by Garyfimo** [comment]
Hey, I've changed the name and got a new error.

![image](https://user-images.githubusercontent.com/5316995/86033800-219da500-b9ff-11ea-8dfb-dbd3de0914af.png)

**Comment by r0adkll** [comment]
Does there error repeat when you re-run it? Have you already created a store listing and uploaded an apk? I know it won't let you upload via the API if you haven't manually uploaded at least once.

**Comment by Garyfimo** [comment]
Does there error repeat when you re-run it? Yep, Ive change all names with the suffix .apk
Have you already created a store listing and uploaded an apk? -> I don't know what is that
if you haven't manually uploaded at least once. -> yes this app is on the play store right now!

**Comment by r0adkll** [comment]
Awesome! I'm glad you figured it out. I'll take note to add some improved logging so as to help others in the future.
