### ISSUE TITLE
Add execution timeout

### ISSUE THREAD

**Issue by marin-marsic** [r0adkll/upload-google-play#136]
In some rare occasions, upload takes too long (360 minutes) to complete so the action gets canceled on GitHub. As discussed in issue #86 it would be great to implement an execution timeout so that the action can be canceled sooner and not spend valuable execution time doing nothing.

**Comment by boswelja** [comment]
I just had a peek at the Edits API, and it looks like it gives us a timeframe the edit is valid for. I will investigate using that at a later date (hopefully it's not 24 hours lol)
