### ISSUE TITLE
##[error]Internal error encountered.

### ISSUE THREAD

**Issue by fobidlim** [r0adkll/upload-google-play#14]
```
serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
packageName: com.fobid.readonly
releaseFile: app/build/outputs/bundle/release/app-release.aab
track: beta
userFraction: 0.99
whatsNewDirectory: whatsnew
mappingFile: app/build/outputs/mapping/release/mapping.txt
```

And this is logs.
```
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***
##[debug]'
##[debug]Loading env
Run r0adkll/upload-google-play@v1
::set-env name=GOOGLE_APPLICATION_CREDENTIALS::./serviceAccountJson.json
##[debug]GOOGLE_APPLICATION_CREDENTIALS='./serviceAccountJson.json'
##[debug][09437649688956974887, packageName=com.fobid.readonly]: Uploading App Bundle @ app/build/outputs/bundle/release/app-release.aab
##[debug][09437649688956974887, versionCode=8, packageName=com.fobid.readonly]: Uploading Proguard mapping file @ app/build/outputs/mapping/release/mapping.txt
##[debug]Creating Track Release for Edit(09437649688956974887) for Track(beta) with a UserFraction(0.99) and VersionCode(8)
##[debug]Found files: whatsnew-en-US,whatsnew-ko-KR
##[debug]Matches for whatsnew-en-US = whatsnew-en-US,en-US
##[debug]Found localized 'whatsnew-*-*' for Lang(en-US)
##[debug]Matches for whatsnew-ko-KR = whatsnew-ko-KR,ko-KR
##[debug]Found localized 'whatsnew-*-*' for Lang(ko-KR)
##[error]Internal error encountered.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Publish aab to Play Store
```

**Comment by vitusortner** [comment]
Any news on this? I've been encountering internal errors as well.

**Comment by Addono** [comment]
Any updates / success with triaging this issue? Getting a similar error message :/

```yaml
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.example.app
          releaseFiles: ./android/app/build/outputs/apk/release/app-release.apk
          track: internalsharing
```

No debug lines though, so not really sure what's going on 🤷 
```
Error: Error: Internal error encountered.
Error: Internal error encountered.
```

**Comment by r0adkll** [comment]
@Addono If you could follow these steps to enable step debug logging (https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) and post the output here it will greatly help me figure out what is going on. Thanks!

**Comment by Addono** [comment]
Hmm 🤔  So I enabled debugging and had to wait until a new release came through. So now with debugging enabled everything went smooth. I don't remember changing anything, so I don't know what made it succeed this time.

Anyway, I will keep debug on and let you know when - if ever - it fails again. 

Thanks for creating and maintaining this action! Super excited to automate another part in our CI 😄 
![image](https://user-images.githubusercontent.com/15435678/103803384-c48b4780-5050-11eb-89ac-337ecf74ccbe.png)

**Comment by r0adkll** [comment]
Awesome! I'm glad it's working for you! I'm going to close this issue and we can re-open if it pops up again
![image](https://user-images.githubusercontent.com/1237372/103844259-79306380-5067-11eb-89ad-a2314aa89dbd.gif)
