### ISSUE TITLE
Bundle is uploaded but not distributed 

### ISSUE THREAD

**Issue by AntonLT** [r0adkll/upload-google-play#144]
**Describe the bug**
App bundle is build and uploaded to draft internal testing we already had, but it still requires every release to be confirmed manually to distribute. Am I doing something wrong? 

**Workflow Step Configuration**

name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
      - run: flutter pub get
      - run: flutter build appbundle 
      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - uses: r0adkll/upload-google-play@v1
         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.cof.flutterapp
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
          status: draft
          inAppUpdatePriority: 5
          mappingFile: build/app/outputs/mapping/release/mapping.txt

**Comment by boswelja** [comment]
Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track

**Comment by thomasbach-dk** [comment]
> Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track

How do you perform a 'complete rollout to your internal track' when it´s not possible to set any other states than 'draft'?

**Comment by boswelja** [comment]
> > Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track
> 
> How do you perform a 'complete rollout to your internal track' when it´s not possible to set any other states than 'draft' using track 'internal'?

Is `draft` the only valid status for the `internal` track? The documentation doesn't mention anything about tracks having limited statuses. You should be able to omit status entirely, or set it to `completed`.

For reference: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Status

**Comment by thomasbach-dk** [comment]
> > > Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track
> > 
> > 
> > How do you perform a 'complete rollout to your internal track' when it´s not possible to set any other states than 'draft' using track 'internal'?
> 
> Is `draft` the only valid status for the `internal` track? The documentation doesn't mention anything about tracks having limited statuses. You should be able to omit status entirely, or set it to `completed`.
> 
> For reference: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Status

I thought so to. But if I set track to `internal` and status to `completed` I get the following error:

`Only releases with status draft may be created on draft app.
`

`- name: Publish app to Google Play Store
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJsonPlainText: ***
          packageName: '***'
          releaseFiles: '***-Signed.aab'
          track: internal
          status: completed`

**Comment by boswelja** [comment]
> > > > Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track
> > > 
> > > 
> > > How do you perform a 'complete rollout to your internal track' when it´s not possible to set any other states than 'draft' using track 'internal'?
> > 
> > 
> > Is `draft` the only valid status for the `internal` track? The documentation doesn't mention anything about tracks having limited statuses. You should be able to omit status entirely, or set it to `completed`.
> > For reference: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Status
> 
> I thought so to. But if I set track to `internal` and status to `completed` I get the following error:
> 
> `Only releases with status draft may be created on draft app. `
> 
> name: Publish app to Google Play Store uses: r0adkll/upload-google-play@v1.0.19 with: serviceAccountJsonPlainText: *** packageName: '_**' releaseFiles: '**_-Signed.aab' track: internal status: completed

That error is telling you your entire app is a draft, so you can't publish anything until it's not a draft. It isn't related to the track you're publishing on (I think)

**Comment by thomasbach-dk** [comment]
> > > > > Isn't the idea of `draft` to only create a draft that still needs to be confirmed? Try doing a complete rollout to your internal track
> > > > 
> > > > 
> > > > How do you perform a 'complete rollout to your internal track' when it´s not possible to set any other states than 'draft' using track 'internal'?
> > > 
> > > 
> > > Is `draft` the only valid status for the `internal` track? The documentation doesn't mention anything about tracks having limited statuses. You should be able to omit status entirely, or set it to `completed`.
> > > For reference: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Status
> > 
> > 
> > I thought so to. But if I set track to `internal` and status to `completed` I get the following error:
> > `Only releases with status draft may be created on draft app. `
> > name: Publish app to Google Play Store uses: r0adkll/upload-google-play@v1.0.19 with: serviceAccountJsonPlainText: *** packageName: '_**' releaseFiles: '**_-Signed.aab' track: internal status: completed
> 
> That error is telling you your entire app is a draft, so you can't publish anything until it's not a draft. It isn't related to the track you're publishing on (I think)

That may be right! But I am able to (manually) press "Edit release" in Play Console and then "Start roll out to Internal testing". Is it possible to achieve same state using this GitHub Action?

![image](https://user-images.githubusercontent.com/16226473/218111331-ceb8204b-f8a8-4410-9675-9d87ecfb6e0c.png)
![image](https://user-images.githubusercontent.com/16226473/218111520-ac57e98f-d270-436c-971f-2d4645bbc2de.png)
![image](https://user-images.githubusercontent.com/16226473/218111660-ce782182-2c5a-496d-8421-819ba2f209e9.png)
![image](https://user-images.githubusercontent.com/16226473/218111763-5944675c-aaf8-42f4-b006-2937a63a8cf8.png)

**Comment by boswelja** [comment]
I don't think so unfortunately, you need to manually confirm releases from the play console when publishing drafts.

Then again I may be missing something, the documentation for the Edits API doesn't explain limitations very well

**Comment by xcskier56** [comment]
@thomasbach-dk, did you find a solution to this? I have just run into the same issue

**Comment by thomasbach-dk** [comment]
> @thomasbach-dk, did you find a solution to this? I have just run into the same issue

Since we cannot make use of dynamic appsettings in one single app targeting different enviroments, we decided to have two dedicated apps in Play Store - one for test purpose (Internal Testing) and one for production. Publishing the one for test purpose works with the following settings:

track: internal
status: draft

**Comment by GNUGradyn** [comment]
Did anyone find a solution for this? My app is still a draft but I want to upload builds without having to manually approve them.

**Comment by akilajwasala** [comment]
I'm also having the same issue

**Comment by FawadMahmood** [comment]
Any solution?

**Comment by boswelja** [comment]
There is no "solution". A draft release is not rolled out to users (as per [the docs](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#status)). If you want to roll out a release, don't submit a draft
