### ISSUE TITLE
Migrate from Node 12 to Node 16

### ISSUE THREAD

**Issue by KubaPreg** [r0adkll/upload-google-play#158]
Hey, 

I get a warning in github actions running your action.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:  r0adkll/upload-google-play@v1

Any chances of releasing new version?

**Comment by boswelja** [comment]
A new version is already out, but the v1 tag is not up to date. Please switch to v1.0.19, which is running node16

**Comment by KubaPreg** [comment]
thank you!
