### ISSUE TITLE
v1 tag doesn't point to latest version

### ISSUE THREAD

**Issue by johnf** [r0adkll/upload-google-play#159]
**Describe the bug**

I'm not sure if this is on purpose or not, but the v1 tag is pointing to a release from Sep 2021.
I noticed this wasn't updating, as I'm still getting node12 deprecation warnings even though this has been fixed.

**Workflow Step Configuration**
```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
```

**Comment by boswelja** [comment]
Thanks for reporting! This should be fixed with the next release as per #148
