### ISSUE TITLE
Support App Bundle Explorer's Internal app sharing link

### ISSUE THREAD

**Issue by shichen85** [r0adkll/upload-google-play#165]
**Feature Request**

Even for uploads that do not use the `internalsharing` track, internal app sharing link is still generated thanks to the [App Bundle Explorer](https://support.google.com/googleplay/android-developer/answer/9844279?_ga=2.184121315.453176378.1672850123-1144302356.1658411817#:~:text=Share%20an%20install%20link). I found these links to be especially helpful when I need to install older builds for cross-version debugging, so I wonder if it is beneficial to include them in the action's existing outputs `internalSharingDownloadUrls` and `internalSharingDownloadUrl`. 

**Inferring the link**

I can't find any Google APIs to directly query those links, but the links follow the same format of `https://play.google.com/apps/test/${applicationId}/${versionCode}`.  The current implementation already stores the version codes at:
https://github.com/r0adkll/upload-google-play/blob/b9dc4464a604e12a040abf6a883d7cf05100a64e/src/edits.ts#L97
So theoretically we can easily infer the URLs and set `internalSharingDownloadUrls` and `internalSharingDownloadUrl`.

Inferring the link does not change the action's core functions. My only concern is that if Google changes the link's format in the future, the inferred links would be incorrect, but that's a problem for the future :P

Does this sound like a good idea? Would be happy to open a PR if so.

**Comment by shichen85** [comment]
Apologies for opening the issue as a bug. Should have used the blank issue instead.

**Comment by boswelja** [comment]
Interesting, I didn't know that existed! If it's part of the API, I'd expect it to be returned when we upload bundles/APKs. I'm happy for you to do this, or I can work on it when I have a free weekend 🙂

**Comment by shichen85** [comment]
> Interesting, I didn't know that existed! If it's part of the API, I'd expect it to be returned when we upload bundles/APKs.

Yes, I would expect it to be part of the response of [edits.bundles.upload](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.bundles/upload), but the official documentation does not mention it.

Will open a PR!

**Comment by shichen85** [comment]
Opened #166.
