### ISSUE TITLE
Unable to deploy with override parameters

### ISSUE THREAD

**Issue by DineshChekuru** [r0adkll/upload-google-play#180]
Hi Team,

I'm trying to deploy code with synapse workspace task. I'm successfully deploying with "azure/synapse-workspace-deployment@release-1.0" but I'm unable to deploy with override parameters step. I have tried to change the parameter values in "TemplateForWorkspace.json" and "TemplateParametersForWorkspace.json" which I'm able to deploy successfully with my changes. Please find the below script for reference.

As this as testing environment but still for security purpose I have modified hardcoded "OverrideArmParameters" values in the script.

name: workspace deployment

on:
push:
branches: [ workspace_publish ]
jobs:
release:
runs-on: windows-latest
steps:
- uses: actions/checkout@v2
- uses: azure/synapse-workspace-deployment@release-1.0
with:
TargetWorkspaceName: 'syn098'
TemplateFile: ./syn098/TemplateForWorkspace.json
ParametersFile: ./syn098/TemplateParametersForWorkspace.json'
OverrideArmParameters : -workspaceName "snapse678" -AzureDataLakeStorage1_accountKey "3ZgGsBiVxgqpt1zaOuRQpWxZPXQV+AStyI/96Q==" -syn098-WorkspaceDefaultSqlServer_connectionString "Integrated Security=False;Encrypt=True;Connection Timeout=30;Data Source=tcp:syn098.sql.azuresynapse.net,1433;Initial Catalog=@{linkedService().DBName}" -synpse5678-WorkspaceDefaultSqlServer_connectionString "Integrated Security=False;Encrypt=True;Connection Timeout=30;Data Source=tcp:synpse5678.sql.azuresynapse.net,1433;Initial Catalog=@{linkedService().DBName}" -AzureDataLakeStorage1_properties_typeProperties_url "https://adls08.dfs.core.windows.net/" -syn098-WorkspaceDefaultStorage_properties_typeProperties_url "https://adls08.dfs.core.windows.net" -synpse5678-WorkspaceDefaultStorage_properties_typeProperties_url "https://adls08.dfs.core.windows.net"
environment: 'Azure Public'
resourceGroup: 'synrg'
clientId: ${{secrets.CLIENTID}}
clientSecret: ${{secrets.CLIENTSECRET}}
subscriptionId: ${{secrets.SUBSCRIPTIONID}}
tenantId: ${{secrets.TENANTID}}
DeleteArtifactsNotInTemplate: 'true'
managedIdentity: 'False'

Please let me know how we can deploy with override parameter step?

**Comment by boswelja** [comment]
I'm not sure what a synapse workspace is, but I am sure you are in the wrong place. This is the `r0adkll/upload_google_play` action repository
