### ISSUE TITLE
whatsNew files format

### ISSUE THREAD

**Issue by vodemn** [r0adkll/upload-google-play#187]
**Describe the bug**
When creating a new release via Google Developer Console there are pre-filled language tags in the release notes field:

```
<en-US>
...
</en-US>
```

So I have a few questions:
1. Do I have to include those tags in my whatsNew files or I can fill only the actual changes and those tags will be extracted from file name?
2. What format these whatsNew files should have? .md?

**Comment by swapnil-musale** [comment]
Hi @vodemn Can you guide me where do we have to create **whatsNewDirectory** this directory ?

**Comment by boswelja** [comment]
> **Describe the bug** When creating a new release via Google Developer Console there are pre-filled language tags in the release notes field:
> 
> ```
> <en-US>
> ...
> </en-US>
> ```
> 
> So I have a few questions:
> 
> 1. Do I have to include those tags in my whatsNew files or I can fill only the actual changes and those tags will be extracted from file name?
> 2. What format these whatsNew files should have? .md?

You do not need to include any tags in your files. You can take a look at the in-repository tests for an example of formatting
https://github.com/r0adkll/upload-google-play/tree/master/__tests__/whatsnew

**Comment by boswelja** [comment]
> Hi @vodemn, @boswelja @r0adkll Can you guide me where do we have to create **whatsNewDirectory** this directory ? While running this action CD pipeline getting failed. (Check Screenshot) <img alt="Screenshot 2023-08-17 at 2 52 06 AM" width="1011" src="https://user-images.githubusercontent.com/15209914/261139814-50085f07-11c5-46f5-b98d-3bae4c965e9b.png">

You create it in your repository. It looks for a directory named `whatsnew`, hence the error you are seeing. For example, with the tests I just linked, the `whatsNewDirectory` would be `__tests__`.
