### ISSUE TITLE
Getting error while uploading new aab file "Error: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by gulabsagevadiya** [r0adkll/upload-google-play#205]
**Describe the bug**
Error: Unexpected end of JSON input

```yml
      - name: Upload bundle to Play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          packageName: app_package_name
          releaseFiles: ${{steps.sign_bundle.outputs.signedReleaseFile}}
          track: production
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt```

**Comment by boswelja** [comment]
Is your service account JSON correct?

**Comment by gulabsagevadiya** [comment]
> Is your service account JSON correct?

I am confident that the account JSON is correct, as this current workflow has been functioning perfectly for the past year.

**Comment by gulabsagevadiya** [comment]
not sure what was worked for me but now it's working

**Comment by Abhishek01039** [comment]
hello @gulabsagevadiya 
how do get the value of `secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON`?

**Comment by boswelja** [comment]
> hello @gulabsagevadiya @boswelja how do get the value of `secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON`?

It's a GitHub Actions secret, so just like any other secret you wrap it in `${{ }}`.
Just like in the snippet above, `${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}`/

In the future, please avoid polluting existing, unrelated issues with easily Googleable questions :smiley:
