### ISSUE TITLE
app bundle signing not work

### ISSUE THREAD

**Issue by jocoosJunghoon** [r0adkll/upload-google-play#213]
My keystore not work when i use app bundle build and try to signing.
apk signing is work well.

 - name: Sign AAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/productionRelease
        signingKeyBase64: ${{ secrets.PRO_KEY_KEYSTORE }}
        alias: ${{ secrets.PRO_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.PRO_STORE_PASSWORD }}
        keyPassword: ${{ secrets.PRO_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
```

Run r0adkll/sign-android-release@v1
  
Preparing to sign key @ app/build/outputs/bundle/productionRelease with signing key
Found 1 release files.
/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64/bin/jarsigner -keystore app/build/outputs/bundle/productionRelease/signingKey.jks -storepass *** -keypass *** app/build/outputs/bundle/productionRelease/{app bundle name}.aab
jar signed.
Warning: 
The signer's certificate is self-signed.
POSIX file permission and/or symlink attributes detected. These attributes are ignored when signing and are not protected by the signature.
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[20](https://github.com/jocoos-repos/mybeautip-plus-android/actions/runs/7911542901/job/21596972789#step:11:21)[22](https://github.com/jocoos-repos/mybeautip-plus-android/actions/runs/7911542901/job/21596972789#step:11:23)-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Releases signed!

Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
Validating track 'production'
Error: The Android App Bundle was signed with multiple certificate chains. Please use exactly one.

**Comment by jocoosJunghoon** [comment]
secret is correct and aab file is located in correct directory.

**Comment by jocoosJunghoon** [comment]
Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
Validating track 'production'
Error: The Android App Bundle was signed with multiple certificate chains. Please use exactly one.

**Comment by boswelja** [comment]
This doesn't seem to be an issue with this action. I'd also recommend setting up signing config directly in Gradle. See the documentation here: https://developer.android.com/studio/publish/app-signing#sign-auto
