### ISSUE TITLE
Can this run on windows-latest

### ISSUE THREAD

**Issue by michaelonz** [r0adkll/upload-google-play#215]
**Describe the bug**
Im trying to upload to app store inside a action that is running on windows-latest 

**Workflow Step Configuration**
  
- uses: vacxe/google-play-cli-kt@master
      with:
        template: apk-upload
        service-account-json: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON_FILE }}
        version-code: "192"
        package-name: "com.company.myappname"
        path-to-apk: bin\Debug\net8.0-android\com.company.myappname.apk
        track: internal
        status: draft

  

**Step Debugging**
At this point I am just wanting to know if it is possible for this to run on a windows workflow - i have other issue with changing it to a linux workflow and everything else works apart from I cant upload to google play ....

**Comment by boswelja** [comment]
The action you are using is not this action
