### ISSUE TITLE
existing package not found

### ISSUE THREAD

**Issue by Klausmd5** [r0adkll/upload-google-play#22]
Hi, everytime I try to run the CD, this error comes up.
The package exists, ive tried to copy it directly from a java class, so there should be no misspelling.
The package exists also on google playstore.

```
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: service_account.json
    packageName: net.vortexdata.filerift
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: beta
    whatsNewDirectory: whatsnew/
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
    SIGNED_RELEASE_FILE: app/build/outputs/bundle/release/app-release.aab
##[error]Package not found: net.vortexdata.filerift.

```

**Comment by Klausmd5** [comment]
ok, the app/build.gradle had a different package

**Comment by forntoh** [comment]
> ok, the app/build.gradle had a different package

I am facing this issue, I have checked the package name in Gradle, workflow file, and in the play console they're the same
