### ISSUE TITLE
Unable to publish alpha track, got error: "Error: EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by LuongPV** [r0adkll/upload-google-play#226]
I configured all things properly: bundle *.aab, private key json, package name.
And I used those information to publish the app using Fastlane CLI successfully.
But I failed to replicate this publish process using this action: r0adkll/upload-google-play@v1.1.3
I got error: "Error: EISDIR: illegal operation on a directory, read". I couldn't see the full cause, the text was cut off.
Does anyone face the same issue?
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/028561ad-42c7-47ab-8873-6706dc1681ed">
<img width="757" alt="image" src="https://github.com/user-attachments/assets/4a391507-2a7f-47bd-ad34-f4e4d8c669f9">

**Comment by boswelja** [comment]
Can you try again, but with debug logging enabled?

**Comment by LuongPV** [comment]
> Can you try again, but with debug logging enabled?

I put secrets and flags ACTIONS_RUNNER_DEBUG but the log was still the same.
Is there anything to configure?

**Comment by boswelja** [comment]
Nope, there's a convenient checkbox when you rerun a failed task though

**Comment by LuongPV** [comment]
> Nope, there's a convenient checkbox when you rerun a failed task though

I checked the debug checkbox, got this logs while re-running the failed job.
I tried both serviceAccountJsonPlainText and serviceAccountJson, still got the same ambiguous error.
Don't know why it said **status=completed** but actually I checked and there was absolutely no new uploaded alpha version on play console.
I gave up, it would stick with fastlane cli.
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/e3bb277b-eac6-4da8-a59d-9d78e4ad005f">

**Comment by boswelja** [comment]
What does your whatsnew setup look like?

**Comment by LuongPV** [comment]
> What does your whatsnew setup look like?
I use the exact whatsnew directory, but I couldn't figure out what's the file name should be, quite frustrating so I use version code number to name the note file, the same way as fastlane suggest for metadata directory.
I tried disabling the whatsnew and it deployed successfully, so definitely the root cause was from whatsnew.
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/03c902dc-c925-41aa-b4f2-6649df5b07e1">

**Comment by boswelja** [comment]
That's robably your issue then - your whatsnew-en_US should be a file containing text, not a folder
Hence the error "read not supported", it's trying to read a folder

**Comment by LuongPV** [comment]
> That's probably your issue then - your whatsnew-en-US should be a file containing text, not a folder Hence the error "read not supported", it's trying to read a folder

It worked, by making whatsnew-en-US a text file. 
I can't believe I got this weird mistake lol.
Thank you for your suppor.

**Comment by boswelja** [comment]
No worries, glad that fixed it! I'll mark this as closed :)
