### ISSUE TITLE
Error: Upload Require Foreground Service permissions.

### ISSUE THREAD

**Issue by rymesaint** [r0adkll/upload-google-play#232]
I got an error like this when uploading

```Error: You must let us know whether your app uses any Foreground Service permissions.```

**Comment by boswelja** [comment]
The error is pretty clearly telling you, you need to fill out some forms in the Play Console when you want to use the foreground service permission.

**Comment by rymesaint** [comment]
ok i've found the problem that i need to upload manually first so that form in play console could be filled.
