### ISSUE TITLE
inAppUpdatePriority option

### ISSUE THREAD

**Issue by josealfonsomora** [r0adkll/upload-google-play#33]
Is there a plan to add `inAppUpdatePriority` option?

https://developer.android.com/guide/playcore/in-app-updates

```
{
  "releases": [{
      "versionCodes": ["88"],
      "inAppUpdatePriority": 5,
      "status": "completed"
  }]
}
```

I can create a quick PR to add it

**Comment by boswelja** [comment]
I'd like to look into this, pending merge of my latest changes first.

**Comment by r0adkll** [comment]
I'm adding this in now
