### ISSUE TITLE
Arabic Release Notes Not being published

### ISSUE THREAD

**Issue by Warhammer4000** [r0adkll/upload-google-play#38]
So I have this folder where  I followed this structure
projectDir/
└── whatsNew/
    ├── whatsnew-en-US
    └── whatsnew-ar

After the action has been executed the english notes has been uploaded but not ar. I checked the BCP 47 standard for the code as well.

**Comment by boswelja** [comment]
Are you still seeing this issue?

**Comment by boswelja** [comment]
Actually, looks like #77 is a duplicate of this and is not limited to Arabic. Closing this to track the isue with more info
