### ISSUE TITLE
Only releases with status draft may be created on draft app.

### ISSUE THREAD

**Issue by abdullah4one** [r0adkll/upload-google-play#39]
Please add draft option

**Comment by r0adkll** [comment]
Could you clarify more on what you are trying to accomplish?

**Comment by abdullah4one** [comment]
I try to publish app using Github action and in play store <br>
I don't make any release before this attempt and  this was the first release 
<Br>and it show this error "Package not found: io.xxx.xx."<br>
Then i upload apk directly to play store then keep it as draft<br>
then i again run github action then  it show this error message

**Comment by joshuapinter** [comment]
Please can we have a "draft" feature that doesn't automatically release the new version. We still need to conduct final testing and update the Release Notes.

**Comment by muth0mi** [comment]
> Could you clarify more on what you are trying to accomplish?

Be able to push releases to internal testing without a reviewed release

**Comment by Jeehut** [comment]
Hey everyone, just a quick note on how I worked around this:
Just setup "Closed Testing" and add countries (e.g. all) & some testers, then review & release. This will make your app be available for these testers and therefore it won't be a "draft" anymore, instead it will be marked as "Closed Testing".
<img width="1262" alt="Bildschirmfoto 2021-05-03 um 16 18 18" src="https://user-images.githubusercontent.com/6942160/116887948-2ccaee00-ac2b-11eb-9fc5-3eab5e26713a.png">

I hope it helps!

**Comment by auriorx** [comment]
@abdullah4one I think I've found a work-around.

`if (options.userFraction != undefined) { status = 'inProgress'; } else { status = 'completed'; }`

I saw this piece of code in the source. The status of the release will not be set to completed if userFraction is defined. So for me, using `userFraction: 0.99` worked!

I hope this little workaround will suit your needs.

**Comment by r0adkll** [comment]
Should now be resolved in `v1.0.16` per PR #78
