### ISSUE TITLE
NAMETOOLONG: name too long, lstat '/home/runner/work/project/***

### ISSUE THREAD

**Issue by iamriajul** [r0adkll/upload-google-play#4]
The file at *** does not exist, or it is not a file. ENAMETOOLONG: name too long, lstat '/home/runner/work/dailyislam-android/dailyislam-android/***
  ***
  ***
  ***
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG[---------]LLLXQwGXz+gQFIvgzeTIP'

My Config Portion:
    - name: Deploy App to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: ID
        releaseFile: app/build/outputs/bundle/beta/app-beta.aab
        track: beta

**Comment by iamriajul** [comment]
### Fixed Issue.
The Problem was with I was passing raw JSON string to serviceAccountJson parameter but the serviceAccountJson parameter accept file path, which I have fixed by creating a JSON File from secrets JSON string.
with following task/commands:


    - name: Create service_account.json FROM secrets.SERVICE_ACCOUNT_JSON
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

    - name: Deploy App to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: org.dailyislam.android
        releaseFile: app/build/outputs/bundle/beta/app-beta.aab
        track: beta

**Comment by joaocarmo** [comment]
I had the same problem. Maybe the documentation could be more explicit?

**Comment by aeharake** [comment]
You can use `serviceAccountJsonPlainText` instead of `serviceAccountJson` if you're storing the service account content in secrets.

```
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
```

**Comment by gsyberg** [comment]
> You can use `serviceAccountJsonPlainText` instead of `serviceAccountJson` if you're storing the service account content in secrets.
> 
> ```
>         with:
>           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
> ```

This is the proper solution.
