### ISSUE TITLE
Warning: WARNING!! 'releaseFile' is deprecated and will be removed in a future release. Please migrate to 'releaseFiles'.

### ISSUE THREAD

**Issue by abdullah4one** [r0adkll/upload-google-play#40]
Warning: WARNING!! 'releaseFile' is deprecated and will be removed in a future release. Please migrate to 'releaseFiles'.

**Comment by r0adkll** [comment]
Yes. This is intentional as the action as moved to multi-release file support using the key `releaseFiles` that takes a comma separated list of files to upload. You can just enter one file (no comma) and it will work the same as before.
