### ISSUE TITLE
Unable to find release file @ /build/app/outputs/apk/release/app-release-signed.apk

### ISSUE THREAD

**Issue by Nikostito** [r0adkll/upload-google-play#41]
Hello, I am trying to upload to Gplay my signed APK. It recognizes my Json correctly and my package name but says that inside my apk there is no release file. Can you please help me fix this issue?
Here are my settings:
`- name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1

        with:
            serviceAccountJsonPlainText: **********
            packageName: 'com.******'
            releaseFile: /build/app/outputs/apk/release/app-release-signed.apk
            track: beta`

Is it because I have my package name in quotes? Any suggestions would be greatly appreciated

**Comment by r0adkll** [comment]
Possibly. Try taking them out of quotes. 
Also if `/build/app/outputs/apk/release/app-release-signed.apk` is relative you should remove the first `/`, i.e.

```
build/app/outputs/apk/release/app-release-signed.apk
```

**Comment by r0adkll** [comment]
Since you haven't responded and I presume my above answer fixes your issue I'm going to close this issue.

**Comment by thewolfaxe** [comment]
Hey, I'm having a similar issue, my upload artifact step seems to find the app bundle successfully, but the upload to playstore fails on the same path

`    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: App Bundle
        path: Mobile/build/app/outputs/bundle/release/app.aab

    - name: Checkout code to get release notes
      uses: actions/checkout@v2

    - name: Upload to Playstore
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ******
        packageName: com.*****
        releaseFiles: Mobile/build/app/outputs/bundle/release/app.aab
        track: internal
        inAppUpdatePriority: 5
        whatsNewDirectory: production/whatsnew`

When it hits this upload to playstore step, it gets the error
`Error: Unable to find any release file @ Mobile/build/app/outputs/bundle/release/app.aab`

Am I just being dumb and missing something?

Cheers

**Comment by thewolfaxe** [comment]
Well it seems like the problem was something to do with the checkout and the whatsNewDirectory. Taking both of those out successfully uploaded to the play store
