### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Missing required parameters: packageName

### ISSUE THREAD

**Issue by NicholasTempleton** [r0adkll/upload-google-play#44]
I'm trying to upload to the "Internal Testing" track of Google Play and I'm getting the following error:

> Finished uploading to the Play Store
> (node:2843) UnhandledPromiseRejectionWarning: Error: Missing required parameters: packageName
>     at createAPIRequestAsync (/home/runner/work/_actions/r0adkll/upload-google-play/v1/node_modules/googleapis-common/build/src/apirequest.js:117:15)
>     at Object.createAPIRequest (/home/runner/work/_actions/r0adkll/upload-google-play/v1/node_modules/googleapis-common/build/src/apirequest.js:53:16)
>     at Resource$Edits$Tracks.get (/home/runner/work/_actions/r0adkll/upload-google-play/v1/node_modules/googleapis/build/src/apis/androidpublisher/v3.js:1204:44)
>     at /home/runner/work/_actions/r0adkll/upload-google-play/v1/lib/edits.js:255:59
>     at Generator.next (<anonymous>)
>     at /home/runner/work/_actions/r0adkll/upload-google-play/v1/lib/edits.js:27:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/runner/work/_actions/r0adkll/upload-google-play/v1/lib/edits.js:23:12)
>     at getPublishedReleaseName (/home/runner/work/_actions/r0adkll/upload-google-play/v1/lib/edits.js:254:12)
>     at Object.<anonymous> (/home/runner/work/_actions/r0adkll/upload-google-play/v1/lib/edits.js:83:47)
> (node:2843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:2843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Here's my step:

>       - name: Deploy to Google Play Internal Testing
>         uses: r0adkll/upload-google-play@v1
>         with:
>           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
>           packageName: com.my.package.name
>           releaseFiles: ${{ steps.sign_bundle.outputs.signedReleaseFile }}
>           track: internal
> 

I've changed the package name for the sake of this example, but I really do have a `packageName` set, contrary to what the error message claims. Any ideas?

**Comment by emme1009** [comment]
same here. was working fine last weekend but now i have the same error..any fix yet?

**Comment by JonatanSalas** [comment]
Same issue here.

**Comment by devapalanisamy** [comment]
same here

**Comment by JonatanSalas** [comment]
It seems like a race condition error, but, anyway the bundle/apk uploads to Internal Testing.

**Comment by NicholasTempleton** [comment]
> It seems like a race condition error, but, anyway the bundle/apk uploads to Internal Testing.

Embarrassingly, it took me a while to actually check because I fixated on this error, but my bundle is actually uploading too.

**Comment by WieFel** [comment]
same here

**Comment by xom9ikk** [comment]
@emme1009, @JonatanSalas @devapalanisamy @NicholasTempleton @WieFel Issue fixed in pull request #47. Please wait next release.

**Comment by crebstock** [comment]
You can temporarily avoid the issue entirely by specifying a releaseName directly as that prevents the call with the missing parameter from happening.

**Comment by r0adkll** [comment]
Sorry about this everyone, and thanks to @xom9ikk for the PR. It should be live under `v1` and `v1.0.9`
