### ISSUE TITLE
Accept serviceAccountJson as json text

### ISSUE THREAD

**Issue by mpost** [r0adkll/upload-google-play#5]
Currently the `serviceAccountJson` property accepts a path to a json file on disc. Since you would usually store this json file as a github secret it would be very convenient if the action could write the file to disc and make it available to the google play api.

**Comment by r0adkll** [comment]
No problem 👍, I'll get this added

**Comment by r0adkll** [comment]
Okay, you can now provide the direct JSON text of your serviceAccountFile via the input `serviceAccountJsonPlainText`. This will be available in `v1` or `v1.0.4`
