### ISSUE TITLE
Error: Internal error encountered.

### ISSUE THREAD

**Issue by Anton22255** [r0adkll/upload-google-play#62]
**Describe the bug**
Build's stoped working! 
Error: Internal error encountered.

**Workflow Step Configuration**

```yml
- name: banking app -> upload to play store
        uses: r0adkll/upload-google-play@v1
        continue-on-error: true
        with:
          serviceAccountJson: service-account.json
          packageName: com.{package}.app
          releaseFiles: ${{ env.BANKING_BUNDLE_PATH }}
          track: alpha
          whatsNewDirectory: whatsnew
```

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

```
Successfully uploaded 1 artifacts
Adding 1 artifacts to release on 'alpha' track
##[debug]Creating Track Release for Edit(11364798056680777470) for Track(alpha) with a UserFraction(undefined) and VersionCodes(16172)
##[debug]Found files: whatsnew-en-GB
##[debug]Matches for whatsnew-en-GB = whatsnew-en-GB,en-GB
##[debug]Found localized 'whatsnew-*-*' for Lang(en-GB)
##[debug]Track: [object Object]
Committing the Edit
Error: Internal error encountered.
##[debug]Node Action run completed with exit code 1
##[debug]GOOGLE_APPLICATION_CREDENTIALS='service-account.json'
##[debug]Finishing: banking app -> upload to play store 

```

**Comment by r0adkll** [comment]
This looks similar to this issue #57 where something on the Google Play Server is erroring that is outside the control of this action. I've created a branch that should hopefully have more verbose logging, if you could update your workflow to use `r0adkll/upload-google-play@fix/internal-errors` and see if the error still occurs and what logs it outputs

**Comment by boswelja** [comment]
We should probably look into communicating an API error occurred when things like this happen

**Comment by boswelja** [comment]
I am going to close this, since it seems like we are reporting errors that the API gives us
