### ISSUE TITLE
Uploading multiple APKs

### ISSUE THREAD

**Issue by tsoos99dev** [r0adkll/upload-google-play#71]
Hi, I gave both the 32-bit and the 64-bit versions of an app as inputs, expecting that they'd be uploaded together. Unfortunately I got this error.

![upload_error](https://user-images.githubusercontent.com/39013301/119911325-686e8480-bf59-11eb-9fa4-952e5b0ce242.png)

What am I doing wrong? I'd rather not create an app bundle if possible.

**Comment by boswelja** [comment]
Google Play doesn't support 32-bit uploads anymore. Did you read the error? Because it's telling you there was an APK that doesn't meet the 64-bit requirement (i.e. your 32-bit one).
For reference, are you able to upload the 32-bit APK to the Play Console manually?

**Comment by tsoos99dev** [comment]
Yes, if I upload both manually, I can create a release containing both without any issues. Here, it seems that only the 32-bit version was uploaded before the error occurred. 
 [https://developer.android.com/google/play/publishing/multiple-apks]()
