### ISSUE TITLE
Ambiguous warning

### ISSUE THREAD

**Issue by IgorGanapolsky** [r0adkll/upload-google-play#75]
**Describe the bug**
> deploy-play-store  WARNING!! 'releaseFile' is deprecated and will be removed in a future release. Please migrate to 'releaseFiles'.

**Workflow Step Configuration**
- name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          # 3
          packageName: com.igor.ganapolsky
          releaseFile: app-release.aab
          track: internal
          mappingFile: mapping.txt

**Comment by boswelja** [comment]
This doesn't seem ambiguous at all, you're using `releaseFile`, which is deprecated. Simply use `releaseFiles` instead
