### ISSUE TITLE
how to use internalSharingDownloadUrls this key next stack message

### ISSUE THREAD

**Issue by kazi-sit** [r0adkll/upload-google-play#79]

**Comment by boswelja** [comment]
This SO answer explains how to use job outputs https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action#:~:text=Job%20outputs%20are%20strings%2C%20and,can%20use%20the%20needs%20context.
I'll look into adding a sample to the README
