### ISSUE TITLE
This error popped up recently! any help?

### ISSUE THREAD

**Issue by richard457** [r0adkll/upload-google-play#80]
I am getting this error all of sudde
![Capture](https://user-images.githubusercontent.com/8529700/134248585-c9a9cb48-a932-495b-8a47-9b59fe2d2e2b.PNG)
n

**Comment by gabriel-loo** [comment]
I'm seeing this as well. It looks like it is caused by #78 where it doesn't set the default status properly if it's not defined. I think the bug is due to [this line](https://github.com/r0adkll/upload-google-play/pull/78/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR24):

```
       const status = core.getInput('status', { required: false });
```

`getInput()` [returns an empty string](https://github.com/actions/toolkit/blob/f0b00fd201c7ddf14e1572a10d5fb4577c4bd6a2/packages/core/src/core.ts#L115) if it's not defined, but it looks like this action is expecting it to return `undefined` instead [here](https://github.com/r0adkll/upload-google-play/pull/78/files#diff-56d61d14ced46b215b948c0af88abcd4cf5c2755943491a3752b1fa8fcdef1ebR147).

**Comment by r0adkll** [comment]
Uh oh! Let me fix this and in the mean time you should be able to update your actions to point to `@v1.0.15` to use the previous release.

**Comment by auriorx** [comment]
@richard457 @gabriel-loo @anrozhkov to prevent future problems in your pipeline, I would also advise to not use @latest to make sure that your build pipeline is always connected to an action version you know to be working.

Only if this is not already the case of course.

Happy coding.
~Auriorx

**Comment by joshuapinter** [comment]
> @richard457 @gabriel-loo @anrozhkov to prevent future problems in your pipeline, I would also advise to not use @latest to make sure that your build pipeline is always connected to an action version you know to be working.
> 
> Only if this is not already the case of course.
> 
> Happy coding.
> ~Auriorx

This. Static Versioning FTW!

**Comment by tronku** [comment]
I am still getting the same error on 1.0.16 @r0adkll, please help. Should we roll back to 1.0.15??

<img width="1076" alt="Screenshot 2021-09-24 at 12 32 10 PM" src="https://user-images.githubusercontent.com/31654207/134632223-012d343f-b303-47c1-8257-0336de684609.png">

**Comment by shubhwicked** [comment]
Yes, I got the same error with the latest version, shall I use 1.0.15, again?

**Comment by hrach** [comment]
Putting key words as a text here instead of image: `Invalid value at 'track_config.releases[0].status' (type.googleapis.com/google.play.publishingapi.v3.Release.Status)`

**Comment by mateuszkwiecinski** [comment]
I'd suggest to move the `v1` tag back to the last working version (if that's not a problem). It would make the action working for people using `v1` version tag (that's the reason why I showed up here 😅)
Also, seeing more and more people are referencing this issue, I'd suggest and ask you @richard457 to update the title to something containing the error message. Google didn't index this issue for me and it took me an additional while to find it. Thanks!

**Comment by gustavocnp95** [comment]
Same problem here! It would be better to go back to the last working version.

**Comment by willmetz** [comment]
rolling back to version 1.0.15 fixed the issue for me, thanks for all the posts here much appreciated

**Comment by parthvirani95** [comment]
![image](https://user-images.githubusercontent.com/49033709/154070896-f5efbe51-ad9f-4f48-becf-8fd4d4df765e.png)
I had solved this by passing the status parameter into it and it worked fine, hope someone find this helpful, and I use this repo https://github.com/r0adkll/upload-google-play for upload to playstore.

Before status parameter: 
![image](https://user-images.githubusercontent.com/49033709/154071434-a2147953-54f9-427f-b836-646bdf3c3235.png)


After Applied above parameter result:
![image](https://user-images.githubusercontent.com/49033709/154071353-a14c6033-8801-4326-9f0a-0b544aa4796f.png)

**Comment by reyts** [comment]
> ![image](https://user-images.githubusercontent.com/49033709/154070896-f5efbe51-ad9f-4f48-becf-8fd4d4df765e.png) I had solved this by passing the status parameter into it and it worked fine, hope someone find this helpful, and I use this repo https://github.com/r0adkll/upload-google-play for upload to playstore.
> 
> Before status parameter: ![image](https://user-images.githubusercontent.com/49033709/154071434-a2147953-54f9-427f-b836-646bdf3c3235.png)
> 
> After Applied above parameter result: ![image](https://user-images.githubusercontent.com/49033709/154071353-a14c6033-8801-4326-9f0a-0b544aa4796f.png)

This worked like a charm
