### ISSUE TITLE
Error: Unable to find any release file @ release.apk

### ISSUE THREAD

**Issue by KClaassen** [r0adkll/upload-google-play#90]
**Describe the bug**
We are trying to automate the uploading to google play store, however after uploading-artifact, we can find the generated 'release.apk' in Github under actions/runs/1559765535, however in the upload-google-play it doesn't seem to recognise the 'releasesFiles' location, doesn't matter what we try, what are we doing wrong here?

**Workflow Step Configuration**

```yml
```

name: Deploy to Play Store

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        
        # Runs a single command using the runners shell
      - name: Generate Release APK
        run: ./gradlew assembleRelease
        
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
#       - uses: actions/upload-artifact@master
#         with:
#           name: mapping.txt
#           path: app/build/outputs/mapping/release/mapping.txt

  deploy-play-store:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
#       # 1
#       - uses: actions/download-artifact@master
#         with:
#           name: release.apk
# #       - uses: actions/download-artifact@master
# #         with:
# #           name: mapping.txt
      # 2
      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          # 3
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.timeling.android
          releaseFiles: app/build/outputs/apk/release
          track: internal
          userFraction: 0.5
#           mappingFile: mapping.txt
 

**Step Debugging**

-- PUBLISH TO PLAY STORE INTERNAL TEST TRACK
Run r0adkll/upload-google-play@v1
Error: Unable to find any release file @ app/build/outputs/apk/release

Note- that's where it gets stuck

Thanks!

**Comment by KClaassen** [comment]
Hi, any update on this? We have tried everything that we can think of with the path and releaseFiles but can't get it to work
<img width="793" alt="Screenshot 2021-12-10 at 14 09 33" src="https://user-images.githubusercontent.com/26342262/145579000-0eb0762b-dbfc-4d95-85f0-202c4f1e6f56.png">
.

**Comment by mitch2na** [comment]
@KClaassen So i ran into this issue as well. Got it to work by adding the absolute file path of the app bundle.

I build my appbundle with flutter so the release file path looks like this:
```yaml
jobs:
  release-android:
    runs-on: ubuntu-latest
    - name: Release appbundle to internal google play store
      uses: r0adkll/upload-google-play@v1.0.16
      with:
        releaseFiles: ${{ github.workspace }}/build/app/outputs/bundle/release/app-release.aab
        track: internal
        status: completed
```

**Comment by KClaassen** [comment]
Ok thanks I will try that

**Comment by nbegey** [comment]
Made it work with : 
./build/outputs/bundle/release/android-ci-release.aab

To see where your project is, you can use **run: echo pwd**

**Comment by boswelja** [comment]
Based on #100, is this functioning in `1.0.15` but broken in `1.0.16`?

**Comment by Saad-Mufti** [comment]
It doesn't look like anyone else made this mistake, but it may be worth making sure you are both generating an aab release file (running `./gradlew bundleRelease` and checking in `app/build/outputs/bundle/release`. 

I was looking in `app/build/outputs/bundle/release` but had generated an apk with `./gradlew assembleRelease`.

**Comment by boswelja** [comment]
If you're running into this, please check the above comment. I can't see any issues that would've appeared with 1.0.16 related to this, closing.

**Comment by Eng-AhmedShehata** [comment]
I have the same problem.
I tried all solutions but with no benefit. 🙁

**Comment by KumarArab** [comment]
I have the same problem.
I tried all solutions but with no benefit. 🙁
