### ISSUE TITLE
Upload native debug symbols

### ISSUE THREAD

**Issue by stevenspiel** [r0adkll/upload-google-play#93]
Is there a way to upload the native debug symbols? I'm able to upload the mapping just fine, but Google Play still is asking for the debug symbols

![Screen Shot 2022-01-26 at 1 52 38 PM](https://user-images.githubusercontent.com/1630091/151227847-66a66065-f051-49c6-9bca-b0f61c6da843.png)

**Comment by ThomasAunvik** [comment]
Does this also apply for App Bundles? It only seems that uploading the App Bundle directly in the Play Console works, but not trough this action.
